import { existsSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { basename, join } from "node:path";
import { JsonObject, mutateTask, now, output, sha256, stateRoot, writeAtomic } from "./core.js";
type Options = Map<string, string | boolean | string[]>;
const text = (o: Options, n: string, f = "") => typeof o.get(n) === "string" ? o.get(n) as string : f;
const list = (o: Options, n: string) => text(o, n).split(",").map((v) => v.trim()).filter(Boolean);
const slug = (v: string) => v.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-").replace(/^-|-$/g, "").slice(0, 72) || "learning";
function base(root: string, scope: string, project: string): string { return scope.toLowerCase() === "global" ? join(root, "knowledge", "global", "entries") : join(root, "projects", project || "default", "knowledge", "entries"); }
function files(path: string): string[] { return existsSync(path) ? readdirSync(path).filter((name) => name.endsWith(".md")).map((name) => join(path, name)) : []; }
function metadata(body: string): JsonObject { const header = body.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1] || ""; return Object.fromEntries(header.split(/\r?\n/).map((line) => { const pos = line.indexOf(":"); return pos > 0 ? [line.slice(0, pos).trim(), line.slice(pos + 1).trim()] : ["", ""]; }).filter(([key]) => key)); }
function resolveEntry(directory: string, reference: string): [string, JsonObject] { for (const path of files(directory)) { const data = metadata(readFileSync(path, "utf8")); if (basename(path, ".md") === reference || data.content_sha256 === reference) return [path, data]; } throw new Error(`no entry in this scope: ${reference}`); }
function setField(body: string, name: string, value: string): string { return new RegExp(`^${name}:.*$`, "m").test(body) ? body.replace(new RegExp(`^${name}:.*$`, "m"), `${name}: ${value}`) : body.replace(/^---\r?\n/, `---\n${name}: ${value}\n`); }
export function learn(options: Options): number { const action = text(options, "action"); const root = stateRoot(text(options, "state-root") || undefined); const scope = text(options, "scope", "Project"); const project = text(options, "project-id", "default"); const directory = base(root, scope, project);
  if (action === "Conflicts") { const grouped = new Map<string, JsonObject[]>(); for (const path of files(directory)) { const data = metadata(readFileSync(path, "utf8")); if (data.origin === "native" && data.status !== "superseded") grouped.set(String(data.topic), [...(grouped.get(String(data.topic)) || []), { id: basename(path, ".md"), topic: data.topic, kind: data.kind }]); } output([...grouped.values()].filter((items) => items.length > 1).map((items) => ({ subject: [items[0].topic], occurrences: items.length, entries: items }))); return 0; }
  if (action === "Forget") { const ids = list(options, "id"); const reason = text(options, "reason"); if (!ids.length || !reason) throw new Error("Forget requires --id and --reason"); const removed = ids.map((id) => { const [path, data] = resolveEntry(directory, id); rmSync(path); return { id, topic: data.topic }; }); output({ status: "forgotten", removed, reason }); return 0; }
  if (action === "Keep") { const ids = list(options, "id"); const reason = text(options, "reason"); if (ids.length < 2 || !reason) throw new Error("Keep requires two --id values and --reason"); const resolved = ids.map((id) => resolveEntry(directory, id)); for (const [path, data] of resolved) { let body = readFileSync(path, "utf8"); body = setField(body, "coexists_with", `[${resolved.filter(([, other]) => other.content_sha256 !== data.content_sha256).map(([, other]) => other.content_sha256).join(", ")}]`); writeAtomic(path, body); } output({ status: "kept", entries: ids, reason }); return 0; }
  if (action !== "Capture") throw new Error(`unsupported learn action: ${action}`); const kind = text(options, "kind"); const topic = text(options, "topic"); const content = text(options, "content").trim(); if (!kind || !topic || !content) throw new Error("Capture requires --kind, --topic, and --content"); if (/\b(?:api[_-]?key|access[_-]?token|auth[_-]?token|password|secret|private[_-]?key)\b\s*[:=]\s*[^\s<>{}\[\]]{8,}/i.test(content)) throw new Error("learning content looks like it contains a credential"); if (scope === "Global" && options.get("approved-by-user") !== true) throw new Error("Global learning requires --approved-by-user"); const digest = sha256(content); for (const path of files(directory)) if (metadata(readFileSync(path, "utf8")).content_sha256 === digest) { output({ status: "existing", path, id: basename(path, ".md") }); return 0; }
  const id = `${now().replace(/[-:.TZ]/g, "").slice(0, 14)}-${kind}-${slug(topic)}-${digest.slice(0, 10)}`; const path = join(directory, `${id}.md`); writeAtomic(path, `---\nid: ${digest}\ntopic: ${slug(topic)}\nscope: ${scope.toLowerCase()}\norigin: native\nkind: ${kind}\nsource_event: ${text(options, "source-event", "agent-learning")}\nproject_id: ${scope === "Global" ? "" : project}\nstatus: ${text(options, "status", "candidate")}\ncontent_sha256: ${digest}\ncreated_at: ${now()}\nupdated_at: ${now()}\n---\n\n${content}\n`); for (const reference of list(options, "supersedes")) { const [old] = resolveEntry(directory, reference); writeAtomic(old, setField(setField(readFileSync(old, "utf8"), "status", "superseded"), "superseded_by", digest)); } for (const reference of list(options, "forget")) rmSync(resolveEntry(directory, reference)[0]); output({ status: "created", path, id }); return 0; }
export function skillDraft(options: Options): number { const root = stateRoot(text(options, "state-root") || undefined); const action = text(options, "action"); const path = join(root, "skill-drafts", "index.json"); const name = text(options, "name");
  if (action === "List") { const state = existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) as JsonObject : { entries: [] as JsonObject[] }; if (!Array.isArray(state.entries)) throw new Error("skill draft index has no entries array"); output((state.entries as JsonObject[]).filter((item) => !text(options, "status") || item.status === text(options, "status"))); return 0; }
  if (action === "Scan") { const project = text(options, "project-id", "default"); const knowledge = files(base(root, "Project", project)).map((file) => ({ file, data: metadata(readFileSync(file, "utf8")) })).filter(({ data }) => data.origin === "native" && data.status !== "superseded"); const byTopic = new Map<string, string[]>(); for (const { file, data } of knowledge) byTopic.set(String(data.topic), [...(byTopic.get(String(data.topic)) || []), basename(file, ".md")]); const min = Number(text(options, "min-occurrences", "3")); output([...byTopic.entries()].filter(([, ids]) => ids.length >= min).map(([topic, ids]) => ({ cluster_id: sha256(`${project}:${topic}`).slice(0, 16), topic, occurrences: ids.length, source_entries: ids }))); return 0; }
  if (!name) throw new Error(`${action} requires --name`);
  if (action === "Draft") { if (!text(options, "description") || !text(options, "content")) throw new Error("Draft requires --description and --content"); const draftPath = join(root, "skill-drafts", name, "SKILL.md"); writeAtomic(draftPath, `---\nname: ${name}\ndescription: ${text(options, "description")}\n---\n\n${text(options, "content").trim()}\n`); mutateTask(path, (state: JsonObject) => { if (!Array.isArray(state.entries)) state.entries = []; const entries = state.entries as JsonObject[]; const record = entries.find((item) => item.name === name); const next = record || { name, created_at: now() }; Object.assign(next, { description: text(options, "description"), cluster_id: text(options, "cluster-id"), source_entries: list(options, "source-entry"), draft_path: draftPath, status: "draft", updated_at: now() }); if (!record) entries.push(next); }); output({ status: "draft", name, path: draftPath }); return 0; }
  if (action === "Reject") { mutateTask(path, (state: JsonObject) => { if (!Array.isArray(state.entries)) state.entries = []; const record = (state.entries as JsonObject[]).find((item) => item.name === name); if (!record) throw new Error(`no draft named ${name}`); record.status = "rejected"; record.note = text(options, "note"); record.updated_at = now(); }); output({ status: "rejected", name }); return 0; }
  if (action !== "Promote") throw new Error(`unsupported skill-draft action: ${action}`); if (options.get("approved-by-user") !== true) throw new Error("Promote requires --approved-by-user"); const target = join(root, "skills", name, "SKILL.md"); mutateTask(path, (state: JsonObject) => { if (!Array.isArray(state.entries)) state.entries = []; const record = (state.entries as JsonObject[]).find((item) => item.name === name); if (!record) throw new Error(`no draft named ${name}`); const draftPath = typeof record.draft_path === "string" ? record.draft_path : ""; const draft = draftPath && existsSync(draftPath) ? readFileSync(draftPath, "utf8") : `---\nname: ${name}\ndescription: ${String(record.description || "")}\n---\n\n${String(record.content || "").trim()}\n`; writeAtomic(target, draft); record.status = "promoted"; record.skill_path = target; record.updated_at = now(); }); output({ status: "promoted", name, path: target, distributed: [] }); return 0; }
