import { existsSync, readdirSync, readFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { git, JsonObject, output, parseFrontmatter, sha256, stableId, stateRoot, stdinJson } from "./core.js";

export function projectResolver(path: string, root?: string): number { const workspace = resolve(path); const top = git(workspace, ["rev-parse", "--show-toplevel"]); const projectRoot = top.status === 0 ? top.stdout.trim() : workspace; const projectId = stableId(projectRoot); const state = stateRoot(root); output({ project_id: projectId, root: projectRoot, state_root: state, task_root: join(state, "projects", projectId, "tasks") }); return 0; }
export function fingerprint(path: string): number { const workspace = resolve(path); const head = git(workspace, ["rev-parse", "HEAD"]); const status = git(workspace, ["status", "--porcelain=v1"]); output({ workspace, head: head.status === 0 ? head.stdout.trim() : "", dirty_sha256: sha256(status.stdout) }); return 0; }
function groups(task: JsonObject, groups: JsonObject[][]): boolean { return groups.some((all) => all.every((condition) => { if (condition.always === true) return true; if (typeof condition.fact === "string") { const facts = typeof task.workflow_facts === "string" ? JSON.parse(task.workflow_facts) as JsonObject : (task.workflow_facts || {}) as JsonObject; const expected = Array.isArray(condition.equals) ? condition.equals.map(String) : []; return expected.includes(String(facts[condition.fact])); } if (Array.isArray(condition.risk_flags)) return Array.isArray(task.risk_flags) && condition.risk_flags.some((flag) => (task.risk_flags as unknown[]).map(String).includes(String(flag))); if (Array.isArray(condition.change_kind)) return condition.change_kind.map(String).includes(String(task.change_kind)); if (Array.isArray(condition.task_type)) return condition.task_type.map(String).includes(String(task.task_type)); return false; })); }
export function workflowPlan(taskPath = ""): number { let task: JsonObject; if (taskPath) { const raw = readFileSync(taskPath, "utf8"); task = taskPath.endsWith(".json") ? JSON.parse(raw) : parseFrontmatter(raw) as JsonObject; } else { task = stdinJson(); } const policy = JSON.parse(readFileSync("schemas/workflow-policy.json", "utf8")) as JsonObject; const capabilities = Array.isArray(policy.capabilities) ? policy.capabilities as JsonObject[] : []; const requested = Array.isArray(task.workflow_request) ? task.workflow_request.map(String) : []; const selected = capabilities.filter((capability) => requested.includes(String(capability.name))).map((capability) => ({ name: capability.name, kind: capability.kind, section: capability.section, steps: Array.isArray(capability.steps) ? capability.steps.map((step) => ({ id: (step as JsonObject).id, title: (step as JsonObject).title })) : [] })); const suggested = capabilities.filter((capability) => Array.isArray(capability.suggest_when) && groups(task, capability.suggest_when as JsonObject[][])).map((capability) => ({ name: capability.name, kind: capability.kind, section: capability.section, reason: capability.suggest_reason || "task metadata matched" })); const order = selected.map((capability) => String(capability.name)); output({ suggested, requested, selected: selected.map((capability) => capability.name), order, roles: selected.filter((capability) => capability.kind === "role").map((capability) => capability.name) }); return 0; }
export function preReview(path: string): number { const diff = git(resolve(path), ["diff", "--check"]); output({ valid: diff.status === 0, check: "git diff --check", errors: diff.stderr || diff.stdout }); return diff.status === 0 ? 0 : 1; }
