import { existsSync, readFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { Json, JsonObject, mutateJsonState, now, option, optionList, output, readJson, schemaPath, sha256, stateRoot, writeAtomic } from "./core.js";

function taskIdFor(taskFilePath: string): string {
  const directory = dirname(taskFilePath); const taskJson = join(directory, "task.json");
  if (existsSync(taskJson)) { const id = readJson(taskJson).id; if (typeof id === "string" && id) return id; }
  return basename(directory);
}

type Options = Map<string, string | boolean | string[]>;
const string = option; // single-value reads share one implementation, so a duplicate flag errors here too
const values = optionList;
function index(root: string, store: string): [string, JsonObject] { const path = join(root, store, "index.json"); return [path, existsSync(path) ? readJson(path) : { schema_version: 1, entries: [] }]; }
function entries(data: JsonObject): JsonObject[] { if (!Array.isArray(data.entries)) throw new Error("index has no entries array"); return data.entries.filter((value): value is JsonObject => !!value && !Array.isArray(value) && typeof value === "object"); }
export type ReviewCauseInput = { root: string; taskPath: string; round: number; cause: string; evidence: string; paths: string[] };

// Review cause is learning telemetry, not a second completion gate. Keeping the write helper
// callable from review-record makes attribution optional on the delivery critical path while
// preserving the standalone review-cause command for explicit maintenance or older integrations.
export function recordReviewCause(input: ReviewCauseInput): JsonObject {
  if (!existsSync(input.taskPath) || input.round < 2 || !input.cause || !input.evidence) throw new Error("review cause needs an existing task path, round >= 2, cause, and evidence");
  const [path] = index(input.root, "review-causes");
  const schema = readJson(schemaPath("review-cause.schema.json")); const configuration = (schema.x_agent_workflow || {}) as JsonObject; const threshold = Number(configuration.escalate_threshold || 2); const routing = (configuration.remedy_routing || {}) as JsonObject;
  const allowedCauses = Array.isArray((schema.properties as JsonObject | undefined)?.cause && ((schema.properties as JsonObject).cause as JsonObject).enum) ? (((schema.properties as JsonObject).cause as JsonObject).enum as Json[]).map(String) : [];
  if (allowedCauses.length && !allowedCauses.includes(input.cause)) throw new Error(`review cause has unsupported cause: ${input.cause}`);
  const taskId = taskIdFor(input.taskPath); let ident = "";
  const locked = mutateJsonState(path, (state: JsonObject) => {
    if (!Array.isArray(state.entries)) state.entries = [];
    const list = entries(state); const existing = list.find((item) => item.task_id === taskId && item.round === input.round);
    ident = existing ? String(existing.id) : `${now().slice(0, 19).replace(/[:T]/g, "")}-${sha256(`${taskId}|${input.round}`).slice(0, 8)}`;
    const item = existing || { id: ident, task_id: taskId, round: input.round, created_at: now() };
    Object.assign(item, { cause: input.cause, evidence: input.evidence, paths: input.paths, status: "open", updated_at: now() });
    if (!existing) list.push(item); state.entries = list; state.updated_at = now();
  });
  writeAtomic(join(input.root, "review-causes", "findings", `${ident}.md`), `---\nid: ${ident}\ntask_id: ${taskId}\nround: ${input.round}\ncause: ${input.cause}\nstatus: open\n---\n\n# ${taskId} round ${input.round}\n\n## What was missing\n\n${input.evidence}\n`);
  const occurrences = entries(locked).filter((entry) => entry.cause === input.cause && entry.status === "open").length;
  return { ok: true, id: ident, cause: input.cause, remedy_kind: routing[input.cause] || "none", occurrences, escalate: routing[input.cause] !== "none" && occurrences >= threshold };
}
export function reviewCause(options: Options): number {
  const root = stateRoot(string(options, "state-root") || undefined); const action = string(options, "action"); const [path, data] = index(root, "review-causes"); const all = entries(data); const cause = string(options, "cause"); const status = string(options, "status");
  if (action === "List") { output(all.filter((item) => (!cause || item.cause === cause) && (!status || item.status === status)).sort((a, b) => String(b.created_at).localeCompare(String(a.created_at)))); return 0; }
  const schema = readJson(schemaPath("review-cause.schema.json")); const configuration = (schema.x_agent_workflow || {}) as JsonObject; const threshold = Number(configuration.escalate_threshold || 2); const routing = (configuration.remedy_routing || {}) as JsonObject;
  if (action === "Escalate") { const groups = new Map<string, JsonObject[]>(); for (const item of all) if (item.status === "open") groups.set(String(item.cause), [...(groups.get(String(item.cause)) || []), item]); output([...groups.entries()].filter(([key, group]) => routing[key] !== "none" && group.length >= Number(string(options, "min-occurrences") || threshold)).map(([key, group]) => ({ cause: key, remedy_kind: routing[key] || "none", occurrences: group.length, finding_ids: group.map((item) => item.id), task_ids: [...new Set(group.map((item) => item.task_id))], paths: [...new Set(group.flatMap((item) => Array.isArray(item.paths) ? item.paths : []))] }))); return 0; }
  if (action === "Resolve") { if (!["applied", "rejected"].includes(status)) throw new Error("Resolve needs --status applied or rejected"); const ids = values(options, "id"); mutateJsonState(path, (locked: JsonObject) => { if (!Array.isArray(locked.entries)) locked.entries = []; const list = entries(locked); for (const id of ids) { const item = list.find((entry) => entry.id === id); if (!item) throw new Error(`finding is missing: ${id}`); item.status = status; item.updated_at = now(); } locked.entries = list; locked.updated_at = now(); }); output({ ok: true, resolved: ids, status }); return 0; }
  if (action !== "Record") throw new Error(`unsupported review-cause action: ${action}`); const taskPath = string(options, "task-path"); const evidence = string(options, "evidence"); const round = Number(string(options, "round")); if (!taskPath || !existsSync(taskPath) || round < 2 || !cause || !evidence) throw new Error("Record needs an existing --task-path, --round >= 2, --cause, and --evidence"); const taskId = taskIdFor(taskPath); let ident = ""; const locked = mutateJsonState(path, (state: JsonObject) => { if (!Array.isArray(state.entries)) state.entries = []; const list = entries(state); const existing = list.find((item) => item.task_id === taskId && item.round === round); ident = existing ? String(existing.id) : `${now().slice(0, 19).replace(/[:T]/g, "")}-${sha256(`${taskId}|${round}`).slice(0, 8)}`; const item = existing || { id: ident, task_id: taskId, round, created_at: now() }; Object.assign(item, { cause, evidence, paths: values(options, "paths"), status: "open", updated_at: now() }); if (!existing) list.push(item); state.entries = list; state.updated_at = now(); }); writeAtomic(join(root, "review-causes", "findings", `${ident}.md`), `---\nid: ${ident}\ntask_id: ${taskId}\nround: ${round}\ncause: ${cause}\nstatus: open\n---\n\n# ${taskId} round ${round}\n\n## What was missing\n\n${evidence}\n`); const occurrences = entries(locked).filter((entry) => entry.cause === cause && entry.status === "open").length; output({ ok: true, id: ident, cause, remedy_kind: routing[cause] || "none", occurrences, escalate: routing[cause] !== "none" && occurrences >= threshold }); return 0;
}
export function retro(options: Options): number { const root = stateRoot(string(options, "state-root") || undefined); const action = string(options, "action"); const [path, data] = index(root, "retro"); const all = entries(data); if (action === "List") { output(all.filter((item) => !string(options, "status") || item.status === string(options, "status"))); return 0; } if (action === "Resolve") { const id = string(options, "id"); const status = string(options, "status"); if (!id || !["applied", "rejected"].includes(status)) throw new Error("Resolve needs an existing --id and applied/rejected --status"); mutateJsonState(path, (locked: JsonObject) => { if (!Array.isArray(locked.entries)) locked.entries = []; const item = entries(locked).find((entry) => entry.id === id); if (!item) throw new Error("Resolve needs an existing --id and applied/rejected --status"); item.status = status; }); output({ ok: true, id, status }); return 0; } if (action !== "Record") throw new Error(`unsupported retro action: ${action}`); const task = string(options, "task-path"); const proposed = string(options, "proposed-change"); if (!existsSync(task) || !proposed) throw new Error("Record needs --task-path and --proposed-change"); const raw = readFileSync(task, "utf8"); const category = raw.match(/^\s*-\s*miss_category:\s*(.+)$/m)?.[1].trim(); if (!category || !/classification:\s*regression/m.test(raw)) throw new Error("only a regression with miss_category is recorded"); const taskId = taskIdFor(task); let ident = ""; const locked = mutateJsonState(path, (state: JsonObject) => { if (!Array.isArray(state.entries)) state.entries = []; const list = entries(state); const found = list.find((entry) => entry.task_id === taskId && entry.miss_category === category); ident = found ? String(found.id) : `${now().slice(0, 19).replace(/[:T]/g, "")}-${sha256(`${taskId}|${category}`).slice(0, 8)}`; if (!found) list.push({ id: ident, task_id: taskId, miss_category: category, classification: "regression", status: "open", created_at: now() }); state.entries = list; }); writeAtomic(join(root, "retro", "findings", `${ident}.md`), `---\nid: ${ident}\ntask_id: ${taskId}\nmiss_category: ${category}\nstatus: open\n---\n\n# ${taskId}\n\n## Proposed framework change\n\n${proposed}\n`); const occurrences = entries(locked).filter((entry) => entry.miss_category === category && entry.status === "open").length; output({ ok: true, id: ident, occurrences, escalate: occurrences >= 2 }); return 0; }
export function splitPlan(options: Options): number { const planPath = string(options, "plan-path"); if (!planPath || !existsSync(planPath)) throw new Error("--plan-path is required"); const plan = readJson(planPath); const workers = Array.isArray(plan.workers) ? plan.workers.filter((item): item is JsonObject => !!item && !Array.isArray(item) && typeof item === "object") : []; const errors: string[] = []; if (plan.shared_persistent_state) errors.push("shared persistent state is not eligible"); if (plan.has_order_dependency) errors.push("ordering dependency is not eligible"); if (workers.length < 2) errors.push("at least two workers are required"); const owned: string[] = []; for (const worker of workers) { const id = String(worker.id || ""); if (!/^[a-z0-9-]+$/.test(id)) errors.push(`invalid worker id: ${id}`); if (!worker.title || !worker.goal || !worker.completion_criteria || !Array.isArray(worker.file_ownership) || !worker.file_ownership.length) errors.push(`worker ${id} is incomplete`); for (const target of Array.isArray(worker.file_ownership) ? worker.file_ownership : []) { const value = String(target); if (owned.some((previous) => value === previous || value.startsWith(previous) || previous.startsWith(value))) errors.push(`ownership overlaps: ${value}`); owned.push(value); } } output({ eligible: errors.length === 0, errors, workers }); return 0; }
